name: Publish

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    name: Bump version, create tag/release point
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag}}
      part: ${{ steps.bump_version.outputs.part}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Bump version and push tag/create release point
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: none
  publish:
    needs: bump_version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # this token is implicitly provided by GitHub Actions
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: npm ci

    - name: Publish (NPM)
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
