name: Publish

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # this token is implicitly provided by GitHub Actions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Version
        env:
          PR_TITLE: ${{ toJson(github.event.pull_request.title) }}
        run: |
          /bin/bash ./bin/npm-version.sh "$PR_TITLE"

      - name: Push Tags
        run: git push --follow-tags

  publish:
    needs: version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish (NPM)
      run: npm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
